apiVersion: v1
kind: Secret
metadata:
  name: private-oci-registry
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: ghcr.io/infrastructure-charts
  enableOCI: "true"
  username: "{{REGISTRY_USERNAME}}"
  password: "{{REGISTRY_PASSWORD}}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: vector-db
imagePullSecrets:
  - name: registry-credentials
